//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bane_User
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string alias_name { get; set; }
        public string user_sex { get; set; }
        public Nullable<System.DateTime> user_birth { get; set; }
        public string user_height { get; set; }
        public string user_identify { get; set; }
        public string user_edu { get; set; }
        public string job_status { get; set; }
        public string bane_type { get; set; }
        public string birth_url { get; set; }
        public string family_phone { get; set; }
        public string live_url { get; set; }
        public string move_phone { get; set; }
        public string attn_name { get; set; }
        public string attn_url { get; set; }
        public string attn_relation { get; set; }
        public string attn_phone { get; set; }
        public string marital_status { get; set; }
        public bool is_live_parent { get; set; }
        public string user_status { get; set; }
        public bool is_pro_train { get; set; }
        public string user_skill { get; set; }
        public string user_type { get; set; }
        public string user_phone { get; set; }
        public System.DateTime ur_next_date { get; set; }
        public string user_photo { get; set; }
        public string user_note { get; set; }
        public int org_id { get; set; }
        public bool is_send { get; set; }
        public string user_resume { get; set; }
        public string iris_data1 { get; set; }
        public string iris_data2 { get; set; }
        public System.DateTime update_date { get; set; }
        public string user_guid { get; set; }
        public string user_pwd { get; set; }
        public string user_mobile { get; set; }
        public int user_total { get; set; }
        public int last_score { get; set; }
        public int the_score { get; set; }
        public int the_num { get; set; }
        public Nullable<System.DateTime> control_date { get; set; }
        public bool is_control { get; set; }
    }
}
