//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bane_CriminalRecord
    {
        public int cr_id { get; set; }
        public string user_identify { get; set; }
        public Nullable<System.DateTime> start_drug_date { get; set; }
        public string drug_year { get; set; }
        public Nullable<int> force_time { get; set; }
        public Nullable<int> force_insulate { get; set; }
        public string other_record { get; set; }
    }
}
