//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bane_FamilyRecord
    {
        public int fr_id { get; set; }
        public string user_identify { get; set; }
        public string fr_name { get; set; }
        public string fr_sex { get; set; }
        public Nullable<System.DateTime> fr_birth { get; set; }
        public string fr_edu { get; set; }
        public string fr_family_url { get; set; }
        public string fr_job { get; set; }
        public string fr_unit { get; set; }
        public string fr_relation { get; set; }
        public string fr_phone { get; set; }
        public int fr_type { get; set; }
    }
}
