//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bane_RecoveryInfo
    {
        public int ri_id { get; set; }
        public string user_identify { get; set; }
        public string exec_area { get; set; }
        public string exec_unit { get; set; }
        public string order_unit { get; set; }
        public bool is_aids { get; set; }
        public string isolation_url { get; set; }
        public Nullable<System.DateTime> isolation_out_date { get; set; }
        public string cure_ups { get; set; }
        public Nullable<bool> in_recovery { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string end_reason { get; set; }
    }
}
