//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bane_QuestionInfo
    {
        public int sub_id { get; set; }
        public string sub_type { get; set; }
        public string sub_title { get; set; }
        public string sub_value { get; set; }
        public int sub_score { get; set; }
        public System.DateTime sub_date { get; set; }
        public string sub_note { get; set; }
        public string sub_essay { get; set; }
    }
}
