//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bane_UrinalysisRecord
    {
        public int ur_id { get; set; }
        public string ur_code { get; set; }
        public string user_identify { get; set; }
        public System.DateTime ur_should_date { get; set; }
        public System.DateTime ur_reality_date { get; set; }
        public string ur_site { get; set; }
        public string ur_method { get; set; }
        public string ur_manager { get; set; }
        public string ur_result { get; set; }
        public string ur_result_show { get; set; }
        public string ur_file_name { get; set; }
        public string ur_attach { get; set; }
        public Nullable<System.DateTime> ur_input_date { get; set; }
        public string ur_note { get; set; }
        public int approve_status { get; set; }
    }
}
