//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bane_HistoryScore
    {
        public int hs_id { get; set; }
        public string user_identify { get; set; }
        public System.DateTime hs_time { get; set; }
        public int hs_score { get; set; }
        public string hs_title { get; set; }
        public int hs_total { get; set; }
    }
}
