//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AreaInfo
    {
        public int area_id { get; set; }
        public int area_pid { get; set; }
        public string area_code { get; set; }
        public string area_name { get; set; }
        public Nullable<int> create_id { get; set; }
        public string create_name { get; set; }
        public System.DateTime create_time { get; set; }
        public string area_note { get; set; }
    }
}
