//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CheckGroup
    {
        public int group_id { get; set; }
        public Nullable<int> group_pid { get; set; }
        public string unit_id { get; set; }
        public string unit_name { get; set; }
        public string group_name { get; set; }
        public string person_id { get; set; }
        public string person_name { get; set; }
        public string person_identifycode { get; set; }
        public Nullable<int> if_leader { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_id { get; set; }
        public string create_name { get; set; }
        public string xMin { get; set; }
        public string yMin { get; set; }
        public string xyAoe { get; set; }
    }
}
