//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Complaints
    {
        public int c_id { get; set; }
        public string c_title { get; set; }
        public string c_content { get; set; }
        public byte[] c_image { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string create_guid { get; set; }
        public string create_personid { get; set; }
        public string create_identifycode { get; set; }
        public Nullable<System.DateTime> re_date { get; set; }
        public string re_note { get; set; }
        public string re_user_id { get; set; }
        public string unit_name { get; set; }
    }
}
