//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DocumentFolder
    {
        public int folder_id { get; set; }
        public string folder_name { get; set; }
        public string folder_url { get; set; }
        public int folder_pid { get; set; }
        public string folder_image { get; set; }
        public Nullable<int> folder_order { get; set; }
        public bool was_share { get; set; }
        public bool if_create_child { get; set; }
        public bool read_only { get; set; }
        public bool if_sys { get; set; }
        public int doc_type { get; set; }
        public int create_id { get; set; }
        public string create_name { get; set; }
        public System.DateTime create_time { get; set; }
        public bool have_child { get; set; }
        public string page_type { get; set; }
    }
}
