//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DocumentInfo
    {
        public int file_id { get; set; }
        public string file_name { get; set; }
        public string alias_name { get; set; }
        public string font_type { get; set; }
        public string file_type { get; set; }
        public decimal file_size { get; set; }
        public decimal file_money { get; set; }
        public Nullable<int> down_number { get; set; }
        public string file_classify { get; set; }
        public int file_status { get; set; }
        public Nullable<System.DateTime> issue_start { get; set; }
        public string doc_type { get; set; }
        public string doc_number { get; set; }
        public Nullable<System.DateTime> issue_end { get; set; }
        public string issue_name { get; set; }
        public string create_name { get; set; }
        public int create_id { get; set; }
        public System.DateTime create_time { get; set; }
        public string attach_url { get; set; }
        public bool if_remove { get; set; }
        public string file_note { get; set; }
    }
}
