//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EnterDetail
    {
        public int ed_id { get; set; }
        public int ent_id { get; set; }
        public string ed_title { get; set; }
        public string ed_reason { get; set; }
        public string ed_create { get; set; }
        public Nullable<int> ed_createId { get; set; }
        public System.DateTime ed_time { get; set; }
        public string ed_note { get; set; }
        public string ent_type { get; set; }
        public int is_success { get; set; }
        public int case_type { get; set; }
        public decimal pay_money { get; set; }
        public int pay_person { get; set; }
        public int solve_type { get; set; }
        public string update_name { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
