//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Implement
    {
        public int imp_id { get; set; }
        public string owner_name { get; set; }
        public string B0001 { get; set; }
        public string B0002 { get; set; }
        public string B000201 { get; set; }
        public string respon_name { get; set; }
        public string respon_phone { get; set; }
        public Nullable<System.DateTime> install_date { get; set; }
        public Nullable<System.DateTime> collect_date { get; set; }
        public Nullable<System.DateTime> clockin_date { get; set; }
        public Nullable<int> use_days { get; set; }
        public Nullable<decimal> cost_money { get; set; }
        public string use_status { get; set; }
        public Nullable<System.DateTime> cost_date { get; set; }
        public string impl_note { get; set; }
    }
}
