//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Instructions
    {
        public int in_id { get; set; }
        public string in_title { get; set; }
        public string in_note { get; set; }
        public string in_url { get; set; }
        public Nullable<int> create_id { get; set; }
        public string create_name { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
