//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ItemCodeMenum
    {
        public int code_id { get; set; }
        public int item_id { get; set; }
        public string code_name { get; set; }
        public string code_value { get; set; }
        public Nullable<int> code_order { get; set; }
        public Nullable<int> code_pid { get; set; }
        public Nullable<int> if_child { get; set; }
        public Nullable<int> if_system { get; set; }
        public string code_note { get; set; }
        public string code_type { get; set; }
    }
}
