//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JobResumeRelation
    {
        public int job_id { get; set; }
        public int com_id { get; set; }
        public int use_id { get; set; }
        public string A0177 { get; set; }
        public string UnitID { get; set; }
        public System.DateTime send_date { get; set; }
        public string job_notes { get; set; }
        public string job_status { get; set; }
    }
}
