//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Login
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int login_count { get; set; }
        public int error_count { get; set; }
        public string login_ip { get; set; }
        public System.DateTime login_time { get; set; }
        public string last_ip { get; set; }
        public Nullable<System.DateTime> last_time { get; set; }
        public string note { get; set; }
        public bool if_false { get; set; }
    }
}
