//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogSetingDetail
    {
        public int detail_id { get; set; }
        public Nullable<int> table_field { get; set; }
        public string field_text { get; set; }
        public string field_datetype { get; set; }
        public string field_oldvalue { get; set; }
        public Nullable<int> field_newvalue { get; set; }
    }
}
