//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogSeting
    {
        public int log_id { get; set; }
        public int folder_id { get; set; }
        public string business_name { get; set; }
        public string table_name { get; set; }
        public string primary_key { get; set; }
        public int user_id { get; set; }
        public string log_type { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public string log_note { get; set; }
    }
}
