//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MessageNotice
    {
        public int m_id { get; set; }
        public string m_title { get; set; }
        public string m_content { get; set; }
        public byte[] m_image { get; set; }
        public string m_image_src { get; set; }
        public string m_type { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_user_id { get; set; }
        public string create_user_name { get; set; }
        public int browse_num { get; set; }
        public string focus_imgage { get; set; }
        public string messList_imgage { get; set; }
        public string messDetail_imgage { get; set; }
    }
}
