//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PageFolder
    {
        public int folder_id { get; set; }
        public string folder_name { get; set; }
        public string folder_url { get; set; }
        public int folder_pid { get; set; }
        public string folder_image { get; set; }
        public Nullable<int> folder_order { get; set; }
        public string folder_type { get; set; }
        public string folder_state { get; set; }
        public Nullable<int> create_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public bool have_child { get; set; }
        public string sm_code { get; set; }
    }
}
