//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PageElement
    {
        public int pe_id { get; set; }
        public int folder_id { get; set; }
        public string pe_name { get; set; }
        public string pe_code { get; set; }
        public string pe_event { get; set; }
        public string pe_func { get; set; }
        public int pe_order { get; set; }
        public Nullable<System.DateTime> pe_create_time { get; set; }
        public Nullable<int> pe_create_id { get; set; }
        public string pe_note { get; set; }
    }
}
