//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PayAccount
    {
        public int pay_id { get; set; }
        public string UnitID { get; set; }
        public string UnitName { get; set; }
        public string ssyh { get; set; }
        public string khmc { get; set; }
        public string zh { get; set; }
        public string khh { get; set; }
        public string pzzl { get; set; }
        public string pzhm { get; set; }
        public decimal ye { get; set; }
        public int if_remove { get; set; }
        public Nullable<int> create_name { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> update_name { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
