//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PermissConfig
    {
        public int pc_id { get; set; }
        public string per_type { get; set; }
        public string per_name { get; set; }
        public string pc_openUrl { get; set; }
        public string pc_saveUrl { get; set; }
        public string pc_width { get; set; }
        public string pc_height { get; set; }
        public string pc_note { get; set; }
    }
}
