//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SysModule
    {
        public int sm_id { get; set; }
        public string sm_name { get; set; }
        public string sm_code { get; set; }
        public string sm_image1 { get; set; }
        public string sm_image2 { get; set; }
        public Nullable<int> sm_order { get; set; }
        public bool if_start { get; set; }
        public int create_id { get; set; }
        public string create_name { get; set; }
        public System.DateTime create_time { get; set; }
        public string sm_note { get; set; }
    }
}
