//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TodoList
    {
        public int to_id { get; set; }
        public string to_user_id { get; set; }
        public string to_user_name { get; set; }
        public string to_copy_to_user { get; set; }
        public string to_title { get; set; }
        public string to_content { get; set; }
        public string to_file { get; set; }
        public Nullable<int> to_send_user_id { get; set; }
        public string to_send_user_name { get; set; }
        public Nullable<System.DateTime> to_send_date { get; set; }
        public Nullable<int> is_system { get; set; }
        public Nullable<int> to_remove { get; set; }
        public string re_content { get; set; }
        public Nullable<System.DateTime> re_date { get; set; }
    }
}
