//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string login_name { get; set; }
        public string user_pwd { get; set; }
        public string user_sex { get; set; }
        public string user_qq { get; set; }
        public string user_email { get; set; }
        public string user_phone { get; set; }
        public string user_address { get; set; }
        public Nullable<System.DateTime> user_birth { get; set; }
        public string user_note { get; set; }
        public string user_img { get; set; }
        public string user_guid { get; set; }
        public int reg_from { get; set; }
        public string user_type { get; set; }
        public string user_identify { get; set; }
    }
}
