//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserGroup
    {
        public int group_id { get; set; }
        public string group_name { get; set; }
        public string group_cname { get; set; }
        public int group_order { get; set; }
        public System.DateTime creator_date { get; set; }
        public Nullable<int> creator_id { get; set; }
        public Nullable<int> creator_name { get; set; }
        public Nullable<int> update_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string group_note { get; set; }
        public string sm_code { get; set; }
    }
}
