//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UseWorker
    {
        public int use_id { get; set; }
        public string use_title { get; set; }
        public int com_id { get; set; }
        public string work_type { get; set; }
        public string trade_type { get; set; }
        public string work_city { get; set; }
        public string addr { get; set; }
        public int use_wage_start { get; set; }
        public int use_wage_end { get; set; }
        public string use_sex { get; set; }
        public string use_age { get; set; }
        public string use_edu { get; set; }
        public string use_ageLimit { get; set; }
        public string use_major { get; set; }
        public string work_start { get; set; }
        public System.DateTime issue_start { get; set; }
        public int use_status { get; set; }
        public string postNote { get; set; }
        public string use_note { get; set; }
        public byte[] header_img { get; set; }
    }
}
