#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HCQ2UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DebtStatistics/DebtMoney.cshtml")]
    public partial class _Views_DebtStatistics_DebtMoney_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DebtStatistics_DebtMoney_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\DebtStatistics\DebtMoney.cshtml"
  
    ViewBag.Title = "欠薪金额统计";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("headerSection", () => {

WriteLiteral(@"
    <style>
        .float-unit {
            height: 100%;
            border: 1px solid #E7EAEC;
            border-top-width: 0px;
            border-bottom-width: 0px;
            margin-bottom: 0px;
        }

        .left-sm-3 {
            padding-left: 0px;
        }

        .right-sm-9 {
            padding-right: 0px;
        }

        .ibox-unit {
            overflow-y: auto;
            height: 90%;
            padding: 0px;
        }
    </style>
");

});

WriteLiteral("<div");

WriteLiteral(" class=\"wrapper animated fadeInRight autoHeight\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row autoHeight\"");

WriteLiteral(" style=\"background-color: #fff;\"");

WriteLiteral(">\r\n        <!--选择单位-->\r\n        <div");

WriteLiteral(" id=\"tree\"");

WriteLiteral("></div>\r\n        <!--生成图表-->\r\n        <div");

WriteLiteral(" class=\"col-sm-9 right-sm-9\"");

WriteLiteral(">\r\n            <!-- 数据 -->\r\n            <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"echarts-Moneybar-chart\"");

WriteLiteral(" style=\"width: 100%; height: 400px;\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n" +
"</div>\r\n");

DefineSection("footSection", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\DebtStatistics\DebtMoney.cshtml"
Write(Scripts.Render("~/bundles/echarts"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1164), Tuple.Create("\"", 1239)
, Tuple.Create(Tuple.Create("", 1170), Tuple.Create<System.Object, System.Int32>(Href("~/Resources/mainFrame/js/plugins/treeview/bootstrap-treeview-1.2.0.js")
, 1170), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1263), Tuple.Create("\"", 1312)
, Tuple.Create(Tuple.Create("", 1269), Tuple.Create<System.Object, System.Int32>(Href("~/Resources/tools/treeview-search-custom.js")
, 1269), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1336), Tuple.Create("\"", 1391)
, Tuple.Create(Tuple.Create("", 1342), Tuple.Create<System.Object, System.Int32>(Href("~/Resources/businessScript/Statistics/DebtItem.js")
, 1342), false)
);

WriteLiteral("></script> \r\n    <script>\r\n        $(function () {\r\n            //加载单位\r\n         " +
"   DrawDebtMoney.initDebtUnit(\"DrawDebtMoney\", \"echarts-Moneybar-chart\");\r\n     " +
"       //DrawDebtMoney.DrawTableByData(\"");

            
            #line 53 "..\..\Views\DebtStatistics\DebtMoney.cshtml"
                                        Write(Url.Action("GetMoneyDataBySelUnit", "DebtStatistics"));

            
            #line default
            #line hidden
WriteLiteral("\", \"DrawDebtMoney\", \"echarts-Moneybar-chart\");\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
